# Tests

# Test1 : Intro
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
name: "R Test 1" #name of test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Squidward: Who wants to run test cases at 3 in the morning?!
    # This code:
    - cron: '26 11 * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - run: gcc -v
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.3' # The R version to download (if necessary) and use.
    - run: sudo apt-get install libcurl4-openssl-dev
    - name: Cache packages, https://rstudio.github.io/renv/articles/ci.html#github-actions
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Restore packages, https://rstudio.github.io/renv/articles/ci.html#github-actions
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
    - run: Rscript Code/main.r
    - run: Rscript Code/utils/venn-diagram.r
