# Tests
# Some of this code is taken from ropenscilabs.github.io

# Test1 : Intro

name: "R Test 1" #name of test
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v1

    - uses: r-lib/actions/setup-pandoc@v1

    - name: Query dependencies
      run: Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds')"
      shell: Rscript {0}

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

    - name: Install dependencies
      run: |
        install.packages(c("remotes","tidyr","dplyr","tidyverse","hrbrthemes","tm","proustr","VennDiagram","RColorBrewer","data.table","dplyr","formattable","tidyr"))
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran("covr")
      shell: Rscript {0}

    - run: Rscript Code/main.r
    - run: Rscript Code/utils/venn-diagram.r