# Tests

# Test1 : Intro
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
name: "R Test 1" #name of test
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Cache packages, https://rstudio.github.io/renv/articles/ci.html#github-actions
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Restore packages, https://rstudio.github.io/renv/articles/ci.html#github-actions
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.0' # The R version to download (if necessary) and use.
    - run: sudo apt-get install libcurl4-openssl-dev
    - run: Rscript Code/main.r
    - run: Rscript Code/utils/venn-diagram.r
env:
  RENV_PATHS_ROOT: ~/.local/share/renv
